from .task_LiftPegUpright import *
from .task_Microwave import *
from .task_PegInsertionSide import *
from .task_LiftPegUpright import *
from .task_PickCube import *
from .task_PlugCharger import *
from .task_PullCube import *
from .task_PushCube import *
from .task_Safe import *
from .task_SpinPullStack import *
from .task_SpinStack import *
from .task_StackCube import *
from .task_PullCubeTool import *
from .task_Tools import *
from .task_UprightStack import *